### ISSUE TITLE
[DOCS]: Make it clearer that we need to install CoPilot as an extension to GitHub CLI

### ISSUE THREAD

**Issue by pm0d** [github/gh-copilot#11]
### Describe the need
Need to specify that we need to install the CoPilot as an extension to the GitHub CLI.

- https://github.blog/changelog/2023-11-08-github-copilot-in-the-cli-now-in-public-beta/
- https://docs.github.com/en/copilot/github-copilot-in-the-cli
- https://docs.github.com/en/copilot/github-copilot-in-the-cli/enabling-github-copilot-in-the-cli

Also make it bit more clearer on the CoPilot repo readme.md https://github.com/github/gh-copilot#quickstart
I actually tried installing the CLI at least 2-3 times before finally finding a line hidden in middle of all the instructions that I need to install the CoPilot separately.

### Version
_Do these docs apply to a specific version?_
No.

### Relevant terminal output
n/a

**Comment by andyfeller** [comment]
@pm0d : Thank you for opening up this issue! 🙇 **How would you suggest we revise the repository readme to address these points?**

If you would like, feel free to provide a draft of what you feel is a more helpful README.md.  Though I'm sorry to hear about your frustrations, I believe all of your points are covered to date and unsure how they can be made clearer.

### Clarity around being a CLI extension

> Need to specify that we need to install the CoPilot as an extension to the GitHub CLI.

This is mentioned in the first paragraph of the readme and is called out as being an extension in the installation steps.

![Image](https://github.com/github/gh-copilot/assets/2089743/d0945307-272d-4908-a3c7-a6505d291bfe)

https://github.com/github/gh-copilot/blob/ca1ec3308c5860a7a5b728382276aa086fa9fa0d/README.md?plain=1#L1-L3

https://github.com/github/gh-copilot/blob/ca1ec3308c5860a7a5b728382276aa086fa9fa0d/README.md?plain=1#L18-L21

### Clarity around GitHub CLI being a requirement

> I actually tried installing the CLI at least 2-3 times before finally finding a line hidden in middle of all the instructions that I need to install the CoPilot separately.

I take it you are referring to the note at the beginning of of the installation section that says you need to have GitHub CLI installed.

![Image](https://github.com/github/gh-copilot/assets/2089743/f52e751a-22ed-408f-b902-8805e7a41c03)

https://github.com/github/gh-copilot/blob/ca1ec3308c5860a7a5b728382276aa086fa9fa0d/README.md?plain=1#L11-L12

**Comment by andyfeller** [comment]
Closing due to lack of user feedback and repository documentation calling out that this is a GitHub CLI extension in the setup instructions.
