### ISSUE TITLE
[BUG]: failed to create explain message

### ISSUE THREAD

**Issue by MartinDelille** [github/gh-copilot#18]
Thanks for taking the time to fill out this out! :bow:
By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/github/gh-copilot/blob/main/CODE_OF_CONDUCT.md).

### What happened?

After installing the extension, I tested the followin command from the README.md without success:

```
$ gh copilot explain 'git lfs migrate import --everything --include="*.gz,*.png,*.jar"'

Welcome to GitHub Copilot in the CLI!
version 0.5.3-beta (2023-11-09)

I'm powered by AI, so surprises and mistakes are possible. Make sure to verify any generated code or suggestions, and share feedback so that we can learn and improve.

✗ Error: failed to explain: failed to create explain message: error sending request: internal server error, code: 400, request ID: CC6D:4DDC:3D4DEB:823242:6554EA88
```

### Versions
_What versions of the relevant software are you running?_
_For example: `gh v2.39.1, gh-copilot 0.5.3-beta (2023-11-09)`_

**Comment by andyfeller** [comment]
@MartinDelille : thank you for opening up this issue! 🙇

Earlier today from 3:59 pm to 4:32 pm UTC, GitHub Copilot in the CLI was affected by a server-side change that resulted in failed requests.  Aside from the change being reverted, the team is following up internally with a retrospective focusing on how to ensure we are detecting and signaling upstream issues such as this to users effectively.

Thank you for your patience, understanding, and support as a GitHub Copilot in the CLI user! ❤

**Comment by MartinDelille** [comment]
I just tried again and it finally work! Thank you for your clear explanation!

**Comment by daksh-gargas** [comment]
Facing the issue again today
>  Error: failed to explain: failed to create explain message: error sending request: internal server error, code: 500, request ID: 08A8:24E331:5350C7:6E369E:66A02608
