### ISSUE TITLE
[FEAT]: convenience downgrade from the $$ 

### ISSUE THREAD

**Issue by Frazer** [github/gh-copilot#23]
The pre-beta version of the CLI, that uses the $$,
Is wildly more convenient.

Not only is it easier to type but you can run the commands from within the code and you don't need to go through to disclaimer every time.

I'm sure there's some reason that you put those steps in, but I hope you can find some way too get it to be just as convenient as before.

**Comment by 0xdevalias** [comment]
This is a duplicate/closely related to the following issues:

- https://github.com/github/gh-copilot/issues/5
- https://github.com/github/gh-copilot/issues/2
- https://github.com/github/gh-copilot/issues/17

**Comment by andyfeller** [comment]
Thanks, @0xdevalias ; with that, I'm going to close this issue as a duplicate as we're tracking against the earlier issues. 👍
