### ISSUE TITLE
Support windows-amd64

### ISSUE THREAD

**Issue by joglr** [github/gh-copilot#26]
Thanks for taking the time to fill out this out! :bow:
By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/github/gh-copilot/blob/main/CODE_OF_CONDUCT.md).

### What happened?

I tried to install GitHub Copilot for CLI using `gh extension install github/gh-copilot` on Windows 11.

### Versions
gh v2.1.0

### Relevant terminal output
```
gh-copilot unsupported for windows-amd64. Open an issue: `gh issue create -R github/gh-copilot -t'Support windows-amd64'`
```

**Comment by andyfeller** [comment]
@joglr : seeing that you completed this 3 minutes after you created it, could you elaborate on whether you were able to resolve your issue?

**Comment by joglr** [comment]
Upgrading to the latest version solved the issue.
