### ISSUE TITLE
Support android-arm

### ISSUE THREAD

**Issue by Nichokas** [github/gh-copilot#28]
### Describe the need
_What problem are you trying to solve? What do you want to happen?_

Suport for android ARM

### Version
_Do these docs apply to a specific version?_
_For example: `gh-copilot v0.5.2-beta`_

No

### Relevant terminal output
_Please copy and paste any relevant terminal output._
_Please check your output before submission to ensure sensitive information is redacted._

**Comment by andyfeller** [comment]
@Nichokas: thanks for opening up this issue!

> Support `android-arm`

**Could you share more about how you use GitHub CLI on `android-arm`?**

I think this might be a slightly larger request as `android-arm` isn't one of the distributions natively supported by the [GitHub CLI](https://cli.github.com/) or [`cli/gh-extension-precompile`](https://github.com/cli/gh-extension-precompile).

If you are looking for mobile support, I recommend following [GitHub Copilot for Mobile](https://github.com/features/copilot) as I believe this has an early 2024 Q2 launch date.

**Comment by Nichokas** [comment]
Sorry for the late reply, I would use it in termiux to control repositories and upload code that I have modified from termux, because if it is a private repository I cannot upload code unless I use github-cli and login

**Comment by Nichokas** [comment]
Termiux is like a linux console but for android mobiles.

**Comment by williammartin** [comment]
In fact I'd like to know what's **not** supported here @Nichokas? What happens that this doesn't work?

**Comment by Nichokas** [comment]
2 months ago when I reported it I didn't support android-arm but it seems that now it does

**Comment by andyfeller** [comment]
> @andyfeller I'm not sure that's true for termux. Here's where the CLI documents Android support: https://github.com/cli/cli/blob/trunk/docs/install_linux.md#android (and here it is in the termux pkg repo: https://packages.termux.dev/apt/termux-main/pool/main/g/gh/)

Revisiting this issue in light of #84, I think there are some nuances here I wanted to mention, @williammartin: 

1. The Android supported linked is technically unofficially provided by the Android community
2. Our Linux and BSD support highlights that CPU architectures we generally support with a difference between 32-bit `android/arm` versus 64-bit `android/arm64`
3. From what I understand, Termux requires a physical Android mobile device, which is somewhat difficult to reproduce support use cases

@Nichokas : would you be willing to share how you were installing `github/gh-copilot` with the existing release artifacts?

**Comment by Nichokas** [comment]
> > @andyfeller I'm not sure that's true for termux. Here's where the CLI documents Android support: https://github.com/cli/cli/blob/trunk/docs/install_linux.md#android (and here it is in the termux pkg repo: https://packages.termux.dev/apt/termux-main/pool/main/g/gh/)
> 
> Revisiting this issue in light of #84, I think there are some nuances here I wanted to mention, @williammartin:
> 
>     1. The Android supported linked is technically unofficially provided by the Android community
> 
>     2. Our Linux and BSD support highlights that CPU architectures we generally support with a difference between 32-bit `android/arm` versus 64-bit `android/arm64`
> 
>     3. From what I understand, Termux requires a physical Android mobile device, which is somewhat difficult to reproduce support use cases
> 
> 
> @Nichokas : would you be willing to share how you were installing `github/gh-copilot` with the existing release artifacts?

I installed it `pkg install gh`
![image](https://github.com/github/gh-copilot/assets/67232385/a2a7872b-a1f6-4db1-b466-1baa807e37ac)

**Comment by williammartin** [comment]
@Nichokas thanks for the response. 

First I think we need to clear up some confusion, when you say "Support android-arm" are generally talking about android-arm (32-bit and 64-bit) or are you very specifically talking about 32-bit (which would generally be packaged as `android-arm` rather than [`android-arm64`](https://github.com/github/gh-copilot/releases/download/v1.0.3/android-arm64)?

Secondly, I think Andy's question about installation was how you installed _this_ extension, rather than `gh` generally.

Thanks!

**Comment by Nichokas** [comment]
> @Nichokas thanks for the response. 
> 
> First I think we need to clear up some confusion, when you say "Support android-arm" are generally talking about android-arm (32-bit and 64-bit) or are you very specifically talking about 32-bit (which would generally be packaged as `android-arm` rather than [`android-arm64`](https://github.com/github/gh-copilot/releases/download/v1.0.3/android-arm64)?
> 
> Secondly, I think Andy's question about installation was how you installed _this_ extension, rather than `gh` generally.
> 
> Thanks!

The issue was on a 32bit phone and I installed the extensión with `gh extension install github/gh-copilot`
