### ISSUE TITLE
[BUG]: PowerShell aliases give an unknown command error

### ISSUE THREAD

**Issue by xt0rted** [github/gh-copilot#38]
### What happened?

I just installed this extension and then ran `gh copilot alias` for powershell. The resulting output calls `gh copilot.exe` which doesn't run, but if I remove the `.exe` part it works just fine.

### Versions
`gh --version`: 2.46.0
`gh copilot --version`: 1.0.0
`$psversiontable`: 7.4.1

### Relevant terminal output

<details><summary>Setup log</summary>
<p>

```powershell
❯ gh copilot alias

? Which shell to generate aliases for?
> PowerShell
function ghcs {
        # Debug support provided by common PowerShell function parameters, which is natively aliased as -d or -db
        # https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_commonparameters?view=powershell-7.4#-debug
        param(
                [ValidateSet('gh', 'git', 'shell')]
                [Alias('t')]
                [String]$Target = 'shell',

                [Parameter(Position=0, ValueFromRemainingArguments)]
                [string]$Prompt
        )
        begin {
                # Create temporary file to store potential command user wants to execute when exiting
                $executeCommandFile = New-TemporaryFile

                # Store original value of GH_DEBUG environment variable
                $envGhDebug = $Env:GH_DEBUG
        }
        process {
                if ($PSBoundParameters['Debug']) {
                        $Env:GH_DEBUG = 'api'
                }

                gh copilot.exe suggest -t $Target -s "$executeCommandFile" $Prompt
        }
        end {
                # Execute command contained within temporary file if it is not empty
                if ($executeCommandFile.Length -gt 0) {
                        # Extract command to execute from temporary file
                        $executeCommand = (Get-Content -Path $executeCommandFile -Raw).Trim()

                        # Insert command into PowerShell up/down arrow key history
                        [Microsoft.PowerShell.PSConsoleReadLine]::AddToHistory($executeCommand)

                        # Insert command into PowerShell history
                        $now = Get-Date
                        $executeCommandHistoryItem = [PSCustomObject]@{
                                CommandLine = $executeCommand
                                ExecutionStatus = [Management.Automation.Runspaces.PipelineState]::NotStarted
                                StartExecutionTime = $now
                                EndExecutionTime = $now.AddSeconds(1)
                        }
                        Add-History -InputObject $executeCommandHistoryItem

                        # Execute command
                        Write-Host "`n"
                        Invoke-Expression $executeCommand
                }
        }
        clean {
                # Clean up temporary file used to store potential command user wants to execute when exiting
                Remove-Item -Path $executeCommandFile

                # Restore GH_DEBUG environment variable to its original value
                $Env:GH_DEBUG = $envGhDebug
        }
}

function ghce {
        # Debug support provided by common PowerShell function parameters, which is natively aliased as -d or -db
        # https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_commonparameters?view=powershell-7.4#-debug
        param(
                [Parameter(Position=0, ValueFromRemainingArguments)]
                [string[]]$Prompt
        )
        begin {
                # Store original value of GH_DEBUG environment variable
                $envGhDebug = $Env:GH_DEBUG
        }
        process {
                if ($PSBoundParameters['Debug']) {
                        $Env:GH_DEBUG = 'api'
                }

                gh copilot.exe explain $Prompt
        }
        clean {
                # Restore GH_DEBUG environment variable to its original value
                $Env:GH_DEBUG = $envGhDebug
        }
}
```

</p>
</details> 

```powershell
ghcs test
unknown command "copilot.exe" for "gh"
```

**Comment by rlove** [comment]
I can duplicate the problem is that in the script it reads `gh copilot.exe ....`  it will work if you change it to `gh copilot ...`  in the script.   No there are two places where this occurs.

**Comment by masewo** [comment]
Also the "clean" blocks of the produced "gh-copilot.ps1" are not inside the "end" blocks leading to another error before. But I could solve this problem with the help of GitHub Copilot itself :-D

**Comment by WilliamRagstad** [comment]
I simply removed all `begin`, `process`, `end` and `clean` blocks from `ghcs` and `ghce` so that their function bodies were all in one block/scope. I also removed `.exe` behind every `copilot.exe`.
This seemed to do the trick for me.

**Comment by xt0rted** [comment]
> Also the commands of the `clean` blocks of the produced `gh-copilot.ps1` are not inside the `end` blocks leading to another error before the one described in this issue. But I could solve this problem with the help of GitHub Copilot itself 😀

@masewo the [clean block](https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_functions_advanced_methods#clean) only works in powershell 7.3+, so if you're on a older version that might be why it didn't work for you.

**Comment by masewo** [comment]
@xt0rted Thank you! I just learned that there are different versions of Powershell. I am on Windows Powershell `5.1.19041.4170` on Winndows `10.0.19045.0`.

**Comment by andyfeller** [comment]
@xt0rted @masewo @WilliamRagstad @rlove : apologies for this oversight and thank you for your patience! 🙇  as there are a few issues about this, I'm going to mark this as redundant to #47 where I've started triaging this.  This is a bug on our part that I'll be following up on.

**Comment by andyfeller** [comment]
> I simply removed all `begin`, `process`, `end` and `clean` blocks from `ghcs` and `ghce` so that their function bodies were all in one block/scope. I also removed `.exe` behind every `copilot.exe`. This seemed to do the trick for me.

@WilliamRagstad : Could you elaborate on why you might need that?

Originally, this was done to ensure that any temporary files used for command execution are cleaned up afterwards.  While you are always able to make changes to what is emitted, it may impact your ability to receive support.

**Comment by andyfeller** [comment]
Appreciate everyone's patience as https://github.com/github/gh-copilot/releases/tag/v1.0.1 has been release, which I hope addresses both #47 or #38! 🙇 

Big thanks for help from our user community including @ifalatiksetlog, @xt0rted, @rlove, @masewo, @dubois as well as out of office help from @colinshum! ✨

**Comment by xt0rted** [comment]
> Could you elaborate on why you might need that?

@andyfeller by using the `clean` block the powershell aliases require powershell core 7.3+. Any version older than that, including the original windows only version, will give an error about missing closing `}`.

```powershell
At C:\Users\brian\OneDrive\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:89 char:15
+ function ghcs {
+               ~
Missing closing '}' in statement block or type definition.
At C:\Users\brian\OneDrive\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:145 char:1
+ }
+ ~
Unexpected token '}' in expression or statement.
At C:\Users\brian\OneDrive\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:147 char:15
+ function ghce {
+               ~
Missing closing '}' in statement block or type definition.
At C:\Users\brian\OneDrive\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:169 char:1
+ }
+ ~
Unexpected token '}' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingEndCurlyBrace
```

`powershell.exe` is the old version and is 5.1 on my machine, while `pwsh.exe` is the newer cross platform version.

**Comment by andyfeller** [comment]
> [@andyfeller](https://github.com/andyfeller) by using the `clean` block the aliases require powershell core 7.3+. Any version older than that, including the original windows only version, will give an error about missing closing `}`.

Thank you for that context, @xt0rted, as I'm unfortunately not a PowerShell power user. 🙇  I will bring this up to the team for discussion and prioritization.
