### ISSUE TITLE
[BUG]: Unknown command "copilot-internal"

### ISSUE THREAD

**Issue by mahtaran** [github/gh-copilot#45]
When using the command as proposed in the [release notes](https://github.com/github/gh-copilot/releases/tag/v1.0.0) or [readme](https://github.com/github/gh-copilot/blob/main/README.md#powershell), I get the following error (PowerShell 7):

```shell
$ gh copilot-internal alias -- pwsh | Out-File ( New-Item -Path $GH_COPILOT_PROFILE -Force )
unknown command "copilot-internal" for "gh"

Usage:  gh <command> <subcommand> [flags]

Available commands:
  alias
  api
  auth
  browse
  cache
  co
  codespace
  completion
  config
  copilot
  extension
  gist
  gpg-key
  issue
  label
  org
  pr
  project
  release
  repo
  ruleset
  run
  search
  secret
  ssh-key
  status
  variable
  workflow
```

To fix it, replace `copilot-internal` by `copilot`:
```shell
$ gh copilot alias -- pwsh | Out-File ( New-Item -Path $GH_COPILOT_PROFILE -Force )
(no output)
```

And the file is created successfully (except for the issues pointed out in #38).

Perhaps this is a remnant of some internal development tool? Anyhow, it should probably be fixed ^^

**Comment by andyfeller** [comment]
@mahtaran : thank you for opening this issue and apologies for the confusion! 🙇 

**Could you help me confirm exactly where `copilot-internal` is mentioned, please?**

Wherever this appears is a mistake and I see you've found the correction.  That said, I cannot seem to figure where that is mentioned to create confusion.

- [`v1.0.0` release notes](https://github.com/github/gh-copilot/releases/tag/v1.0.0)
- [`v1.0.1` release notes](https://github.com/github/gh-copilot/releases/tag/v1.0.1)
- [repository README](https://github.com/github/gh-copilot/blob/main/README.md)
- [GitHub Blog changelog post](https://github.blog/changelog/2024-03-21-github-copilot-general-availability-in-the-cli/)

**Comment by mahtaran** [comment]
@andyfeller not sure where I thought I read it in the readme, but it's still located under the alias setup instructions in the v1.0.0 release notes:
![image](https://github.com/github/gh-copilot/assets/22727323/65496a51-65f1-48ac-b488-87e71e175a04)

**Comment by andyfeller** [comment]
@mahtaran : Thank you, I just fixed it, so hopefully no more confusion. ❤  I appreciate your help and support, Luka.
