### ISSUE TITLE
[DOCS]: Add to PowerShell Profile

### ISSUE THREAD

**Issue by breadboi** [github/gh-copilot#49]
Thanks for taking the time to fill out this out! :bow:
By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/github/gh-copilot/blob/main/CODE_OF_CONDUCT.md).

### Describe the need
In the PowerShell installation guide on this page https://docs.github.com/en/copilot/github-copilot-in-the-cli/using-github-copilot-in-the-cli, the "PowerShell profile:" instructions work only if the path doesn't include spaces. For example, the current instructions will cause trouble for anyone that's using OneDrive to backup their Documents folder, as it has spaces in the path.

To fix this, you could quote the affected area like so.
```echo ". `"$GH_COPILOT_PROFILE`"" >> $PROFILE```

### Version
_Do these docs apply to a specific version?_
It does not, this applies to PowerShell overall.

### Relevant terminal output
_Please copy and paste any relevant terminal output._
The following is what is inserted into my profile using the current documentation.
`. C:\Users\username\OneDrive - ExampleOrgName\Documents\PowerShell\gh-copilot.ps1`

**Comment by andyfeller** [comment]
@breadboi : thank you for opening this issue along with a suggested fix! ❤ 

This absolutely makes sense 👍

**Comment by andyfeller** [comment]
@breadboi : this should now be fixed in [`v1.0.2`](https://github.com/github/gh-copilot/releases/tag/v1.0.2)!

Thank you for your patience and support! ❤  Please let us know if there are any problems
