### ISSUE TITLE
[BUG]: alias not working on zsh

### ISSUE THREAD

**Issue by Ali-thepro** [github/gh-copilot#54]
Thanks for taking the time to fill out this out! :bow:
By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/github/gh-copilot/blob/main/CODE_OF_CONDUCT.md).

### What happened?
I get this error 
(eval):1: defining function based on alias `ghcs'
(eval):1: parse error near `()'

after copying this comand

echo 'eval "$(gh copilot alias -- zsh)"' >> ~/.zshrc

### Versions
I am using  gh-copilot v1.0.1

### Relevant terminal output
(eval):1: defining function based on alias `ghcs'
(eval):1: parse error near `()'

I use zsh version 5.8.1

**Comment by andyfeller** [comment]
@Ali-thepro : Thank you for opening this follow up! 🙇  Could you share a few more pieces of information, please?

1. What is in your `~/.zshrc`?

   For example, I might expect the following:

   ```shell
   eval "$(gh copilot alias -- zsh)"
   ```

1. What is the output of `gh copilot alias -- zsh`?

   See below for example of output.


<details>
<summary>
  <b>Example of <code>gh copilot alias -- zsh</code> output</b>
</summary>
<p>

```shell
ghcs() {
	FUNCNAME="$funcstack[1]"
	TARGET="shell"
	local GH_DEBUG="$GH_DEBUG"

	read -r -d '' __USAGE <<-EOF
	Wrapper around \`gh copilot suggest\` to suggest a command based on a natural language description of the desired output effort.
	Supports executing suggested commands if applicable.

	USAGE
	  $FUNCNAME [flags] <prompt>

	FLAGS
	  -d, --debug              Enable debugging
	  -h, --help               Display help usage
	  -t, --target target      Target for suggestion; must be shell, gh, git
	                           default: "$TARGET"

	EXAMPLES

	- Guided experience
	  $ $FUNCNAME

	- Git use cases
	  $ $FUNCNAME -t git "Undo the most recent local commits"
	  $ $FUNCNAME -t git "Clean up local branches"
	  $ $FUNCNAME -t git "Setup LFS for images"

	- Working with the GitHub CLI in the terminal
	  $ $FUNCNAME -t gh "Create pull request"
	  $ $FUNCNAME -t gh "List pull requests waiting for my review"
	  $ $FUNCNAME -t gh "Summarize work I have done in issues and pull requests for promotion"

	- General use cases
	  $ $FUNCNAME "Kill processes holding onto deleted files"
	  $ $FUNCNAME "Test whether there are SSL/TLS issues with github.com"
	  $ $FUNCNAME "Convert SVG to PNG and resize"
	  $ $FUNCNAME "Convert MOV to animated PNG"
	EOF

	local OPT OPTARG OPTIND
	while getopts "dht:-:" OPT; do
		if [ "$OPT" = "-" ]; then     # long option: reformulate OPT and OPTARG
			OPT="${OPTARG%%=*}"       # extract long option name
			OPTARG="${OPTARG#"$OPT"}" # extract long option argument (may be empty)
			OPTARG="${OPTARG#=}"      # if long option argument, remove assigning `=`
		fi

		case "$OPT" in
			debug | d)
				GH_DEBUG=api
				;;

			help | h)
				echo "$__USAGE"
				return 0
				;;

			target | t)
				TARGET="$OPTARG"
				;;
		esac
	done

	# shift so that $@, $1, etc. refer to the non-option arguments
	shift "$((OPTIND-1))"

	TMPFILE="$(mktemp -t gh-copilotXXX)"
	trap 'rm -f "$TMPFILE"' EXIT
	if GH_DEBUG="$GH_DEBUG" gh copilot suggest -t "$TARGET" "$@" --shell-out "$TMPFILE"; then
		if [ -s "$TMPFILE" ]; then
			FIXED_CMD="$(cat $TMPFILE)"
			print -s "$FIXED_CMD"
			echo
			eval "$FIXED_CMD"
		fi
	else
		return 1
	fi
}

ghce() {
	FUNCNAME="$funcstack[1]"
	local GH_DEBUG="$GH_DEBUG"

	read -r -d '' __USAGE <<-EOF
	Wrapper around \`gh copilot explain\` to explain a given input command in natural language.

	USAGE
	  $FUNCNAME [flags] <command>

	FLAGS
	  -d, --debug   Enable debugging
	  -h, --help    Display help usage

	EXAMPLES

	# View disk usage, sorted by size
	$ $FUNCNAME 'du -sh | sort -h'

	# View git repository history as text graphical representation
	$ $FUNCNAME 'git log --oneline --graph --decorate --all'

	# Remove binary objects larger than 50 megabytes from git history
	$ $FUNCNAME 'bfg --strip-blobs-bigger-than 50M'
	EOF

	local OPT OPTARG OPTIND
	while getopts "dh-:" OPT; do
		if [ "$OPT" = "-" ]; then     # long option: reformulate OPT and OPTARG
			OPT="${OPTARG%%=*}"       # extract long option name
			OPTARG="${OPTARG#"$OPT"}" # extract long option argument (may be empty)
			OPTARG="${OPTARG#=}"      # if long option argument, remove assigning `=`
		fi

		case "$OPT" in
			debug | d)
				GH_DEBUG=api
				;;

			help | h)
				echo "$__USAGE"
				return 0
				;;
		esac
	done

	# shift so that $@, $1, etc. refer to the non-option arguments
	shift "$((OPTIND-1))"

	GH_DEBUG="$GH_DEBUG" gh copilot explain "$@"
}
```

</p>
</details>

**Comment by Ali-thepro** [comment]
This is the output of `gh copilot alias -- zsh`

`ghcs() {
        FUNCNAME="$funcstack[1]"
        TARGET="shell"
        local GH_DEBUG="$GH_DEBUG"

        read -r -d '' __USAGE <<-EOF
        Wrapper around \`gh copilot suggest\` to suggest a command based on a natural language description of the desired output effort.
        Supports executing suggested commands if applicable.

        USAGE
          $FUNCNAME [flags] <prompt>

        FLAGS
          -d, --debug              Enable debugging
          -h, --help               Display help usage
          -t, --target target      Target for suggestion; must be shell, gh, git
                                   default: "$TARGET"

        EXAMPLES

        - Guided experience
          $ $FUNCNAME

        - Git use cases
          $ $FUNCNAME -t git "Undo the most recent local commits"
          $ $FUNCNAME -t git "Clean up local branches"
          $ $FUNCNAME -t git "Setup LFS for images"

        - Working with the GitHub CLI in the terminal
          $ $FUNCNAME -t gh "Create pull request"
          $ $FUNCNAME -t gh "List pull requests waiting for my review"
          $ $FUNCNAME -t gh "Summarize work I have done in issues and pull requests for promotion"

        - General use cases
          $ $FUNCNAME "Kill processes holding onto deleted files"
          $ $FUNCNAME "Test whether there are SSL/TLS issues with github.com"
          $ $FUNCNAME "Convert SVG to PNG and resize"
          $ $FUNCNAME "Convert MOV to animated PNG"
        EOF

        local OPT OPTARG OPTIND
        while getopts "dht:-:" OPT; do
                if [ "$OPT" = "-" ]; then     # long option: reformulate OPT and OPTARG
                        OPT="${OPTARG%%=*}"       # extract long option name
                        OPTARG="${OPTARG#"$OPT"}" # extract long option argument (may be empty)
                        OPTARG="${OPTARG#=}"      # if long option argument, remove assigning `=`
                fi

                case "$OPT" in
                        debug | d)
                                GH_DEBUG=api
                                ;;

                        help | h)
                                echo "$__USAGE"
                                return 0
                                ;;

                        target | t)
                                TARGET="$OPTARG"
                                ;;
                esac
        done

        # shift so that $@, $1, etc. refer to the non-option arguments
        shift "$((OPTIND-1))"

        TMPFILE="$(mktemp -t gh-copilotXXX)"
        trap 'rm -f "$TMPFILE"' EXIT
        if GH_DEBUG="$GH_DEBUG" gh copilot suggest -t "$TARGET" "$@" --shell-out "$TMPFILE"; then
                if [ -s "$TMPFILE" ]; then
                        FIXED_CMD="$(cat $TMPFILE)"
                        print -s "$FIXED_CMD"
                        echo
                        eval "$FIXED_CMD"
                fi
        else
                return 1
        fi
}

ghce() {
        FUNCNAME="$funcstack[1]"
        local GH_DEBUG="$GH_DEBUG"

        read -r -d '' __USAGE <<-EOF
        Wrapper around \`gh copilot explain\` to explain a given input command in natural language.

        USAGE
          $FUNCNAME [flags] <command>

        FLAGS
          -d, --debug   Enable debugging
          -h, --help    Display help usage

        EXAMPLES

        # View disk usage, sorted by size
        $ $FUNCNAME 'du -sh | sort -h'

        # View git repository history as text graphical representation
        $ $FUNCNAME 'git log --oneline --graph --decorate --all'

        # Remove binary objects larger than 50 megabytes from git history
        $ $FUNCNAME 'bfg --strip-blobs-bigger-than 50M'
        EOF

        local OPT OPTARG OPTIND
        while getopts "dh-:" OPT; do
                if [ "$OPT" = "-" ]; then     # long option: reformulate OPT and OPTARG
                        OPT="${OPTARG%%=*}"       # extract long option name
                        OPTARG="${OPTARG#"$OPT"}" # extract long option argument (may be empty)
                        OPTARG="${OPTARG#=}"      # if long option argument, remove assigning `=`
                fi

                case "$OPT" in
                        debug | d)
                                GH_DEBUG=api
                                ;;

                        help | h)
                                echo "$__USAGE"
                                return 0
                                ;;
                esac
        done

        # shift so that $@, $1, etc. refer to the non-option arguments
        shift "$((OPTIND-1))"

        GH_DEBUG="$GH_DEBUG" gh copilot explain "$@"
}`

`declare -f ghcs` has no output.

my ~/.zshrc contains the following
[txt.txt](https://github.com/github/gh-copilot/files/14735614/txt.txt)

**Comment by Ali-thepro** [comment]
@andyfeller it appears to be working now. Thanks

**Comment by williammartin** [comment]
@Ali-thepro, the feature has not been removed but it seems like the aliases set a default:

```
ghcs() {
        FUNCNAME="$funcstack[1]"
        TARGET="shell"
...
```

You can change this using `ghcs -t gh/git/shell`, though it seems like `--target` only works if you do `--target=gh/git/shell` (`=` rather than space). I'll create another issue for that.

I'm not sure why the decision was made to default to the `shell` variety but I'll ask around.

**Comment by williammartin** [comment]
Would it be fair to say this specific issue has been resolved, and we can open another to support interactive target selection when using the alias?

**Comment by Ali-thepro** [comment]
@williammartin yes the issue has been resolved.

**Comment by Ali-thepro** [comment]
and @williammartin could you please tag me in the issue to support interactive target selection, thanks

**Comment by williammartin** [comment]
Done in https://github.com/github/gh-copilot/issues/58
