### ISSUE TITLE
[BUG]: failed to run extension

### ISSUE THREAD

**Issue by xbotter** [github/gh-copilot#6]
### What happened?
```
failed to run extension: fork/exec C:\Users\[username]\AppData\Local\GitHub CLI\extensions\gh-copilot\gh-copilot.exe: %1 is not a valid Win32 application.
```

### Versions
Windows 11 
PowerShell 7.3.9
**gh copilot  github/gh-copilot  v0.5.2-beta**

### Relevant terminal output
![image](https://github.com/github/gh-copilot/assets/3634877/f32fe5c2-08bc-49c2-84cc-13435a1edf7e)

**Comment by imanmahjoubi** [comment]
@xbotter Thank you for bringing up this issue and for being an early adopter of this feature. The team will take a look at this. We apologize for the inconvenience 😔

**Comment by andyfeller** [comment]
@xbotter: I'll need to double check this out later on my personal laptop, but in the mean time, this one has a few of us stumped as Microsoft Windows 11 only supports 64-bit CPUs according to [installation site](https://www.microsoft.com/en-in/software-download/windows11):

> **Has a 64-bit CPU**: Windows 11 can only run on 64-bit CPUs. To see if your PC has one, go to Settings > System > About, or search “System Information” in Windows and look under “System Type.”

**In the meantime, could you share the result from [printing your system version information](https://learn.microsoft.com/en-us/dotnet/api/system.environment.version?view=net-7.0#system-environment-version)?**

```pwsh
PS /Users/andyfeller> [System.Environment]::OSVersion

Platform ServicePack Version VersionString
-------- ----------- ------- -------------
    Unix             13.6.1  Unix 13.6.1
```

**Comment by xbotter** [comment]
@andyfeller Thanks for your attention, here is my system version information.
```
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.22621.0 Microsoft Windows NT 10.0.22621.0
```
I manually downloaded windows-amd64.exe from the release and replaced the gh-copilot.exe file. It is now working.

**Comment by andyfeller** [comment]
> [@andyfeller](https://github.com/andyfeller) Thanks for your attention, here is my system version information.
> 
> ```
> Platform ServicePack Version      VersionString
> -------- ----------- -------      -------------
>  Win32NT             10.0.22621.0 Microsoft Windows NT 10.0.22621.0
> ```
> 
> I manually downloaded windows-amd64.exe from the release and replaced the gh-copilot.exe file. It is now working.

Thanks!  It appears you are running Windows 10, which has support for 32- and 64-bit exe.  I think this is touching on a larger GitHub CLI issue I would love your help in replicating and creating an issue in https://github.com/cli/cli 🙇 

I think the problem lays [within the extension manager binary extension install logic](https://github.com/cli/cli/blob/3f37d7e372857c17141f290aeac404babc0282cc/pkg/cmd/extension/manager.go#L239-L254) in determining your platform:

```go
func (m *Manager) installBin(repo ghrepo.Interface, target string) error {
	var r *release
	var err error
	isPinned := target != ""
	if isPinned {
		r, err = fetchReleaseFromTag(m.client, repo, target)
	} else {
		r, err = fetchLatestRelease(m.client, repo)
	}
	if err != nil {
		return err
	}

	platform, ext := m.platform()
	isMacARM := platform == "darwin-arm64"
	trueARMBinary := false
```

In [`m.platform()`](https://github.com/cli/cli/blob/3f37d7e372857c17141f290aeac404babc0282cc/pkg/cmd/extension/manager.go#L50-L56), it is attempting to use Go special variables for your operating system and CPU architecture:

```go
		platform: func() (string, string) {
			ext := ""
			if runtime.GOOS == "windows" {
				ext = ".exe"
			}
			return fmt.Sprintf("%s-%s", runtime.GOOS, runtime.GOARCH), ext
		},
```

I'd be interested to know which version it downloaded if you still had that info or would be willing to replicate it, so we can dig into that a bit more! 🙇

**Comment by xbotter** [comment]
@andyfeller I tried to upgrade the CLI and reinstalled the copilot extension, now it's working fine. It might be because my previous CLI version was too old.

**Comment by BW404** [comment]
I am getting the same issue.

![image](https://github.com/github/gh-copilot/assets/70896135/f069113f-4294-4192-a4b8-92a0638ddf6f)

**Comment by esilyzhang** [comment]
> I am getting the same issue.
> 
> ![image](https://private-user-images.githubusercontent.com/70896135/318244656-f069113f-4294-4192-a4b8-92a0638ddf6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMjE4NDQsIm5iZiI6MTcxNzEyMTU0NCwicGF0aCI6Ii83MDg5NjEzNS8zMTgyNDQ2NTYtZjA2OTExM2YtNDI5NC00MTkyLWE0YjgtOTJhMDYzOGRkZjZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDAyMTIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyYThiZDhlMzEwMjIwNzViOTNlYmE5NzdiNTQ3ODYyZGM1OTY1MGViYjE2M2YyNGJhMjQ4MTEwYzdkZTFkMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gzXAVTtXI5Y__HIAzF2i464cislIsf7EdKyG2_fGKK0)

The issue was resolved by reinstalling it.

```sh
gh extension remove github/gh-copilot
gh extension install github/gh-copilot
```

**Comment by orhirshfeld-elbit** [comment]
Just Installed Github CLI and Co-pilot on Win11 Powershell and I have the same issue, also tried to reinstall gh-copilot and it didnt work

```
❯ gh copilot suggest "Install and configure git lfs"
failed to run extension: fork/exec C:\Users\e054310\AppData\Local\GitHub CLI\extensions\gh-copilot\gh-copilot.exe: %1 is not a valid Win32 application.
```

```
❯ [System.Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.26100.0 Microsoft Windows NT 10.0.26100.0
```

```
❯ gh --version
gh version 2.78.0 (2025-08-21)
https://github.com/cli/cli/releases/tag/v2.78.0
```

```
❯ winget install --id GitHub.cli
Found an existing package already installed. Trying to upgrade the installed package...
No available upgrade found.
No newer package versions are available from the configured sources.
```

**System info:**

Processor	Intel(R) Core(TM) Ultra 7 165U   2.10 GHz
System type	64-bit operating system, x64-based processor
Edition	Windows 11 Enterprise
Version	24H2
OS build	26100.4351


@andyfeller @BW404 @babakks
