### ISSUE TITLE
[BUG]: mktemp invalid argument on Alpine Linux

### ISSUE THREAD

**Issue by cirolosapio** [github/gh-copilot#66]
### What happened?
![image](https://github.com/github/gh-copilot/assets/33943143/7d41ad17-ea7b-43aa-bdfa-4c9d672e6300)

### Versions
gh version 2.39.2 (2024-03-06)
gh copilot version 1.0.1 (2024-03-22)

### Solution
on alpine linux 3.19 `mktemp` command require at least 6 `X` characters

![image](https://github.com/github/gh-copilot/assets/33943143/bbf0c2d9-fbd3-4897-8ab3-25e791ef959a)

**Comment by andyfeller** [comment]
@cirolosapio : this should now be fixed in [`v1.0.2`](https://github.com/github/gh-copilot/releases/tag/v1.0.2)!

Thank you for your patience and support! ❤  Please let us know if there are any problems
