### ISSUE TITLE
[BUG]: Enterprise Copilot seat assignment blocked access to feature, prevents creating personal subscription

### ISSUE THREAD

**Issue by bradfeehan** [github/gh-copilot#79]
Thanks for taking the time to fill out this out! :bow:
By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/github/gh-copilot/blob/main/CODE_OF_CONDUCT.md).

### What happened?
_What did you do? What happened? What did you expect to happen?_

Sorry for the awkward wording.

tl;dr: My day job bought Copilot for the organisation, but chose to disable the CLI feature. I want to use it for a side project on my personal machine, but can't subscribe as I'm already assigned an enterprise seat.

**Background**

1. My GitHub account, which I use for personal and also within an organisation, has been assigned an Enterprise Copilot seat by one of the organisations I contribute to. In [Billing summary](https://github.com/settings/billing/summary) > Add-ons > GitHub Copilot I see:

   > You are assigned a seat as part of a GitHub Copilot Enterprise subscription managed by (ORG).

2. I see that [Setting up GitHub Copilot in the CLI](https://docs.github.com/en/copilot/github-copilot-in-the-cli/setting-up-github-copilot-in-the-cli) says:

   > If you have a GitHub Copilot Individual subscription, you can install the GitHub Copilot in the CLI extension without needing to enable it for your organization.
   > 
   > If you are part of an organization with a GitHub Copilot Business subscription, the organization owner will need to enable Copilot in the CLI in the Copilot settings. You can then install the GitHub Copilot in the CLI extension.

   And under [Enabling or disabling Copilot in the CLI at the organization level](https://docs.github.com/en/copilot/github-copilot-in-the-cli/setting-up-github-copilot-in-the-cli#enabling-or-disabling-copilot-in-the-cli-at-the-organization-level) says:

   > An organization owner can enable or disable Copilot in the CLI for the organization.

3. Under Settings > [Copilot](https://github.com/settings/copilot), I see my organisation has disabled this feature:

   > **Copilot in the CLI**: Disabled
   > This setting has been set by (ORG) administrators. Learn more about [Copilot in the CLI](https://docs.github.com/copilot/github-copilot-in-the-cli/using-github-copilot-in-the-cli).

4. However, I want to use it on my personal machine to contribute outside this organisation which has provided me the Copilot Enterprise seat. I am happy to pay for a personal subscription, as I reiterate [Setting up GitHub Copilot in the CLI](https://docs.github.com/en/copilot/github-copilot-in-the-cli/setting-up-github-copilot-in-the-cli) which says:

   > If you have a GitHub Copilot Individual subscription, you can install the GitHub Copilot in the CLI extension without needing to enable it for your organization.

   But under Settings > Billing > Add-ons there's no way for me to subscribe, as the message explaining I'm assigned the seat by the organisation, has replaced the functionality to create a personal subscription.

**What I'd expect:**

- ✅ My organisation should be able to choose which features they assign me
- ✅ I can use those features when logged in to my organisation (including their enterprise login Okta etc. extra layer of authentication)
- ❌ If one organisation provided me Copilot in the IDE and block the CLI feature, I should still be (but am not) able to buy the feature they didn't provide.
- ❌ in other words, I should be able to pay for use of Copilot in the CLI for personal use, or for use in my own organisation, even if none of my organisations have provided it to me.

**Workarounds**

I'm sure if I created a new GitHub account I'd be allowed to create a personal subscription, but then I'd have to move all my repositories over to that account. (there's problems with that, e.g. GitHub pages custom domain CNAMEs point to that account). This is the first GitHub feature that would require separate accounts :(

### Versions
_What versions of the relevant software are you running?_
_For example: `gh v2.37.0, gh-copilot v0.5.2-beta`_

```
$ gh --version
gh version 2.50.0 (2024-05-29)
https://github.com/cli/cli/releases/tag/v2.50.0

$ gh copilot --version
version 1.0.3 (2024-05-08)
```

### Relevant terminal output
_Please copy and paste any relevant terminal output._
_Please check your output before submission to ensure sensitive information is redacted._

```
gh copilot explain "sudo apt-get"

✗ Error: User is not authorized to use this Copilot feature

To start using GitHub Copilot in the CLI, request access from your organization admin.
```

no option to subscribe :(

**Comment by andyfeller** [comment]
@bradfeehan : thank you for opening this issue and my sincerest apologies for the difficulties! 🙇 

Follow up from one of my colleagues involved with Copilot licensing and policy capabilities confirms this is a larger issue than GitHub Copilot in the CLI.  As the work involved is medium term, the only short term workaround involves having separate GitHub user profiles for personal and professional usage.

I realize that might not be feasible or palatable, but it is the only option right now. 😞

**Comment by Psvensso** [comment]
This is still not fixed or commented on.
 
For info. If you do the "now 6-month and no longer short term"-fix by creating a second account you can't then transfer the second copilot license over to your main account if you end relationship with you main account license holder. And basically if you do opensource work etc. on your account you probably want that traceability onto your main account.

**Comment by andyfeller** [comment]
> This is still not fixed or commented on.

@Psvensso : Unfortunately, this issue and the feedback is larger than `gh-copilot` but a broader GitHub Copilot licensure problem.  As the `gh-copilot` team cannot directly address this, here is my best advice:

1. Reach out to your GitHub administrators and account team to discuss this
2. Reach out to [GitHub Community discussions on Copilot](https://github.com/orgs/community/discussions/categories/copilot) to discuss this

In the mean time, I will close this issue because of the reasons described above.
